<?php

/**
 * @package SP Page Builder
 * @author JoomShaper http://www.joomshaper.com
 * @copyright Copyright (c) 2010 - 2023 JoomShaper
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 or later
 */
//no direct access
defined('_JEXEC') or die('Restricted access');

use Joomla\CMS\Language\Text;

// Common
Text::script('COM_SPPAGEBUILDER_FRONTEND_EDITOR');
Text::script('COM_SPPAGEBUILDER_BACKEND_EDITOR');
Text::script('COM_SPPAGEBUILDER_PREVIEW');
Text::script('COM_SPPAGEBUILDER_APPLY');
Text::script('COM_SPPAGEBUILDER_CANCEL');
Text::script('COM_SPPAGEBUILDER_DELETE_COLUMN_CONFIRMATION');
Text::script('COM_SPPAGEBUILDER_SHOW');
Text::script('COM_SPPAGEBUILDER_HIDE');
Text::script('COM_SPPAGEBUILDER_OPTIONS');
Text::script('COM_SPPAGEBUILDER_COPY');
Text::script('COM_SPPAGEBUILDER_PASTE');
Text::script('COM_SPPAGEBUILDER_PASE_STYLE');
Text::script('COM_SPPAGEBUILDER_DUPLICATE');
Text::script('COM_SPPAGEBUILDER_COLUMN');
Text::script('COM_SPPAGEBUILDER_RENAME');
Text::script('COM_SPPAGEBUILDER_LOADING');
Text::script('COM_SPPAGEBUILDER_SUCCESS_LEVEL');
Text::script('COM_SPPAGEBUILDER_SUCCESS_FOR_LAYOUT');
Text::script('COM_SPPAGEBUILDER_SUCCESS_MSG_FOR_DELETE');
Text::script('COM_SPPAGEBUILDER_ERROR_LEVEL');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_FOR_DELETE');
Text::script('COM_SPPAGEBUILDER_GLOBAL_ADD');
Text::script('COM_SPPAGEBUILDER_WARNING_LEVEL');
Text::script('COM_SPPAGEBUILDER_WARNING_FOR_URL_REDIRECT');
Text::script('COM_SPPAGEBUILDER_CONFIRM_LEVEL');
Text::script('COM_SPPAGEBUILDER_CONFIRM_FOR_ICON_DELETE');
Text::script('COM_SPPAGEBUILDER_SUCCESS_FOR_ICON_PACK');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_FOR_DELETE_ICON');
Text::script('COM_SPPAGEBUILDER_SUCCESS_MSG_FOR_ICON_PACK_ENABLED');
Text::script('COM_SPPAGEBUILDER_SUCCESS_MSG_FOR_ICON_PACK_DISABLED');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_CHANGING_STATUS');
Text::script('COM_SPPAGEBUILDER_SUCCESS_MSG_FOR_ICON_PACK_INSERTED');
Text::script('COM_SPPAGEBUILDER_SUCCESS_MSG_FOR_ALERT');
Text::script('COM_SPPAGEBUILDER_SUCCESS_MSG_FOR_PAGE_SAVE');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_FOR_PRO_VERSION');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_FOR_COPIED_ROW');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_FOR_COPIED_ADDON');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_NO_RESULT_FOUND');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_FOR_INVALID_DEPENDS_ARRAY');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_FOR_INVALID_DATA_STRUCTURE');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_FOR_INVALID_MISSING_OPTIONS');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_FOR_INVALID_DATA_STRUCTURE_FOUND');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_FOR_INVALID_ADDONS_SETTINGS');
Text::script('COM_SPPAGEBUILDER_UPDATE');
Text::script('COM_SPPAGEBUILDER_GENERATE');
Text::script('COM_SPPAGEBUILDER_CATEGORIES');
Text::script('COM_SPPAGEBUILDER_SECTIONS');
Text::script('COM_SPPAGEBUILDER_SECTION');
Text::script('COM_SPPAGEBUILDER_COLUMN');
Text::script('COM_SPPAGEBUILDER_ADDON');
Text::script('COM_SPPAGEBUILDER_INSERT');
Text::script('COM_SPPAGEBUILDER_DONE');
Text::script('COM_SPPAGEBUILDER_FOLDERS');
Text::script('COM_SPPAGEBUILDER_START');
Text::script('COM_SPPAGEBUILDER_END');
Text::script('COM_SPPAGEBUILDER_COLOR');
Text::script('COM_SPPAGEBUILDER_HORIZONTAL');
Text::script('COM_SPPAGEBUILDER_VERTICAL');
Text::script('COM_SPPAGEBUILDER_BLUR');
Text::script('COM_SPPAGEBUILDER_SPREAD');
Text::script('COM_SPPAGEBUILDER_TYPE');
Text::script('COM_SPPAGEBUILDER_UPLOAD');
Text::script('COM_SPPAGEBUILDER_REPLACE');
Text::script('COM_SPPAGEBUILDER_SAVE');
Text::script('COM_SPPAGEBUILDER_SAVE_CLOSE');
Text::script('COM_SPPAGEBUILDER_SAVE_NEW');
Text::script('COM_SPPAGEBUILDER_CLOSE');
Text::script('COM_SPPAGEBUILDER_SAVE_COPY');
Text::script('COM_SPPAGEBUILDER_DELETE_SAVED_ADDON_DIALOG_MSG');
Text::script('COM_SPPAGEBUILDER_DELETE_SAVED_SECTION_DIALOG_MSG');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_FOR_UNAUTHORISED_BLOCK_INSERT');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_FOR_BLOCK_INSERT');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_FOR_EMPTY_BLOCK');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_FOR_PAGE_ID_NOT_FOUND');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_FOR_FETCHING_TEMPLATES');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_FOR_FETCHING_COLLECTION');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_FOR_FETCHING_BLOCKS');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG_FOR_FETCHING_SAVED_ITEMS');
Text::script('COM_SPPAGEBUILDER_NO_ITEMS_FOUND');
Text::script('COM_SPPAGEBUILDER_LAYERS_PANEL_OPTIONS');
Text::script('COM_SPPAGEBUILDER_LAYERS_PANEL_EXPAND_ALL');
Text::script('COM_SPPAGEBUILDER_LAYERS_PANEL_COLLAPSE_ALL');
Text::script('COM_SPPAGEBUILDER_LAYERS_PANEL_CLEAR_CANVAS');
Text::script('COM_SPPAGEBUILDER_LAYERS_PANEL_EXPORT_CANVAS');

Text::script('COM_SPPAGEBUILDER_NEW_PAGE_ENTER_TITLE');
Text::script('COM_SPPAGEBUILDER_CLEAR_PAGE_CONTENT_CONFIRM');
Text::script('COM_SPPAGEBUILDER_ITEMS_CHECKED_IN');

Text::script('COM_SPPAGEBUILDER_PAGE_OPTIONS');
Text::script('COM_SPPAGEBUILDER_POPOVER_TITLE');
Text::script('COM_SPPAGEBUILDER_LAYOUT_FILTER_PAGE');
Text::script('COM_SPPAGEBUILDER_LAYOUT_FILTER_SORT_BY');
Text::script('COM_SPPAGEBUILDER_ERROR_MSG');

Text::script('COM_SPPAGEBUILDER_GLOBAL_DIVIDER');
Text::script('COM_SPPAGEBUILDER_SHOW');
Text::script('COM_SPPAGEBUILDER_HIDE');




// Media Manager
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_UPLOAD_FILES');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_CLOSE');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_INSERT');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_SEARCH');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_CANCEL');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_DELETE');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_CONFIRM_DELETE');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_LOAD_MORE');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_UNSUPPORTED_FORMAT');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_BROWSE_MEDIA');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_BROWSE_FOLDERS');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_CREATE_FOLDER');
Text::script('COM_SPPAGEBUILDER_ADDON_ICON_SELECT');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_ENTER_DIRECTORY_NAME');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_MEDIA_UPLOADING');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_UPLOAD_FAILED');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_MEDIA_LARGE');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_FILE_NOT_SUPPORTED');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_MEDIA_DROP_FILES');
Text::script('COM_SPPAGEBUILDER_NO_UPLOAD_PERMISSION');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_MEDIA_ALL_ITEMS');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_MEDIA_NOTHING_FOUND');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_MEDIA_NO_ICON_FOUND');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_MEDIA_IMAGES');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_MEDIA_VIDEOS');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_MEDIA_AUDIOS');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_MEDIA_ATTACHMENTS');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_MEDIA_FOLDERS');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_MEDIA_SEARCH');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_MEDIA_ALL');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_MEDIA_TOASTER_SUCCESS');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_MEDIA_FOLDER_NOT_EMPTY');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_MEDIA_RENAME_SUCCESS');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_MEDIA_RENAME_ERROR');

// Row
Text::script('COM_SPPAGEBUILDER_ROW_OPTIONS');
Text::script('COM_SPPAGEBUILDER_ADD_NEW_ROW');
Text::script('COM_SPPAGEBUILDER_DUPLICATE_ROW');
Text::script('COM_SPPAGEBUILDER_DISABLE_ROW');
Text::script('COM_SPPAGEBUILDER_ENABLE_ROW');
Text::script('COM_SPPAGEBUILDER_COPY_ROW');
Text::script('COM_SPPAGEBUILDER_ROW_COPIED');
Text::script('COM_SPPAGEBUILDER_ADDON_COPIED');
Text::script('COM_SPPAGEBUILDER_PASTED');
Text::script('COM_SPPAGEBUILDER_PASTE_ROW');
Text::script('COM_SPPAGEBUILDER_DELETE_ROW');
Text::script('COM_SPPAGEBUILDER_ROW_TOGGLE');
Text::script('COM_SPPAGEBUILDER_DELETE_ROW_CONFIRMATION');
Text::script('COM_SPPAGEBUILDER_ROW_COLUMNS_MANAGEMENT');
Text::script('COM_SPPAGEBUILDER_GLOBAL_CUSTOM');
Text::script('COM_SPPAGEBUILDER_ROW_COLUMNS_GENERATE');
Text::script('COM_SPPAGEBUILDER_IMPORT_PAGE');
Text::script('COM_SPPAGEBUILDER_IMPORT_PAGE_ALT');
Text::script('COM_SPPAGEBUILDER_EXPORT_PAGE');
Text::script('COM_SPPAGEBUILDER_IMPORT_ROW');
Text::script('COM_SPPAGEBUILDER_PAGE_TEMPLATES');
Text::script('COM_SPPAGEBUILDER_UNDO');
Text::script('COM_SPPAGEBUILDER_REDO');
Text::script('COM_SPPAGEBUILDER_SAVE');
Text::script('COM_SPPAGEBUILDER_SAVE_ROW');
Text::script('COM_SPPAGEBUILDER_ROW_START_CREATING_PAGE');
Text::script('COM_SPPAGEBUILDER_ROW_LAYOUT_BUNDLES');
Text::script('COM_SPPAGEBUILDER_ROW_IMPORT_LAYOUT');
Text::script('COM_SPPAGEBUILDER_ROW_OR');

//Section
Text::script('COM_SPPAGEBUILDER_SECTION_OPTIONS');
Text::script('COM_SPPAGEBUILDER_SECTION_SETTINGS');
Text::script('COM_SPPAGEBUILDER_SAVE_SECTION');
Text::script('COM_SPPAGEBUILDER_DUPLICATE_SECTION');
Text::script('COM_SPPAGEBUILDER_RESET_COLUMNS_WIDTH');
Text::script('COM_SPPAGEBUILDER_EDIT_COLUMN_IN_SECTION');
Text::script('COM_SPPAGEBUILDER_DISABLE_SECTION');
Text::script('COM_SPPAGEBUILDER_ENABLE_SECTION');
Text::script('COM_SPPAGEBUILDER_COPY_SECTION');
Text::script('COM_SPPAGEBUILDER_PASTE_SECTION');
Text::script('COM_SPPAGEBUILDER_DELETE_SECTION');
Text::script('COM_SPPAGEBUILDER_SECTION_COPIED');
Text::script('COM_SPPAGEBUILDER_EDIT_SECTION');

//Addon
Text::script('COM_SPPAGEBUILDER_ROW_COLUMNS_OPTIONS');
Text::script('COM_SPPAGEBUILDER_DELETE_COLUMN');
Text::script('COM_SPPAGEBUILDER_ADD_NEW_ADDON');
Text::script('COM_SPPAGEBUILDER_ADDON');
Text::script('COM_SPPAGEBUILDER_DELETE_ADDON');
Text::script('COM_SPPAGEBUILDER_DUPLICATE_ADDON');
Text::script('COM_SPPAGEBUILDER_CANVAS');
Text::script('COM_SPPAGEBUILDER_DELETE_CANVAS');
Text::script('COM_SPPAGEBUILDER_RENAME_CANVAS');
Text::script('COM_SPPAGEBUILDER_SETTINGS_CANVAS');
Text::script('COM_SPPAGEBUILDER_DUPLICATE_CANVAS');
Text::script('COM_SPPAGEBUILDER_OPTIONS');
Text::script('COM_SPPAGEBUILDER_EDIT_ADDON');
Text::script('COM_SPPAGEBUILDER_EDIT_ROW');
Text::script('COM_SPPAGEBUILDER_EDIT_COLUMN_IN_ROW');
Text::script('COM_SPPAGEBUILDER_ADDONS_LIST');
Text::script('COM_SPPAGEBUILDER_ALL');
Text::script('COM_SPPAGEBUILDER_MODAL_CLOSE');
Text::script('COM_SPPAGEBUILDER_DISABLE_COLUMN');
Text::script('COM_SPPAGEBUILDER_ENABLE_COLUMN');
Text::script('COM_SPPAGEBUILDER_ADDON_AJAX_CONTACT_COLUMN_OPTION');
Text::script('COM_SPPAGEBUILDER_ROW');
Text::script('COM_SPPAGEBUILDER_ADDON_ITEM_ADD_EDIT');
Text::script('COM_SPPAGEBUILDER_ADDON_TABLE_ADVANCED_SEARCH_PLACEHOLDER');

Text::script('COM_SPPAGEBUILDER_YES');
Text::script('COM_SPPAGEBUILDER_NO');
Text::script('COM_SPPAGEBUILDER_PAGE_TEMPLATES_LIST');
Text::script('COM_SPPAGEBUILDER_PAGE_TEMPLATE_LOAD');
Text::script('COM_SPPAGEBUILDER_ENABLE_ADDON');
Text::script('COM_SPPAGEBUILDER_DISABLE_ADDON');
Text::script('COM_SPPAGEBUILDER_SAVE_ADDON');
Text::script('COM_SPPAGEBUILDER_ADDON_PARENT_COLUMN');
Text::script('COM_SPPAGEBUILDER_ADD_NEW_INNER_ROW');
Text::script('COM_SPPAGEBUILDER_MOVE_COLUMN');

Text::script('COM_SPPAGEBUILDER_DAY');
Text::script('COM_SPPAGEBUILDER_DAYS');
Text::script('COM_SPPAGEBUILDER_HOUR');
Text::script('COM_SPPAGEBUILDER_HOURS');
Text::script('COM_SPPAGEBUILDER_MINUTE');
Text::script('COM_SPPAGEBUILDER_MINUTES');
Text::script('COM_SPPAGEBUILDER_SECOND');
Text::script('COM_SPPAGEBUILDER_SECONDS');

Text::script('COM_SPPAGEBUILDER_ADDON_OPTIN_FORM_SUBCSCRIBE');
Text::script('COM_SPPAGEBUILDER_ADDON_AJAX_CONTACT_NAME');
Text::script('COM_SPPAGEBUILDER_ADDON_AJAX_CONTACT_EMAIL');

Text::script('COM_SPPAGEBUILDER_SAVED_ITEMS_BUTTON');

Text::script('COM_SPPAGEBUILDER_SIDEBAR_CARD_TITLE');
Text::script('COM_SPPAGEBUILDER_SIDEBAR_CARD_MONEY_BACK');

Text::script('COM_SPPAGEBUILDER_SAVED_ITEMS_SECTIONS_TITLE');
Text::script('COM_SPPAGEBUILDER_SAVED_ITEMS_SECTIONS_CONTENT');

Text::script('COM_SPPAGEBUILDER_SAVED_ITEMS_ADDONS_TITLE');
Text::script('COM_SPPAGEBUILDER_SAVED_ITEMS_ADDONS_CONTENT');

Text::script('COM_SPPAGEBUILDER_MEDIA');
Text::script('COM_SPPAGEBUILDER_LEARNING');
Text::script('COM_SPPAGEBUILDER_GLOBAL_LAYOUTS');
Text::script('COM_SPPAGEBUILDER_GLOBAL_LAYERS');
Text::script('COM_SPPAGEBUILDER_GLOBAL_ADDONS');
Text::script('COM_SPPAGEBUILDER_LAYOUT_BLOCKS');
Text::script('COM_SPPAGEBUILDER_LAYOUT_SAVED_ITEM');
Text::script('COM_SPPAGEBUILDER_ADDON_ANIMATION_DIRECTION');
Text::script('COM_SPPAGEBUILDER_ADDON_CAROUSEL_LAYOUTS');

Text::script('COM_SPPAGEBUILDER_LAYOUTS');
Text::script('COM_SPPAGEBUILDER_LAYOUTS_LIVE_DEMO');
Text::script('COM_SPPAGEBUILDER_LAYOUTS_IMPORT');
Text::script('COM_SPPAGEBUILDER_LAYOUT_POPOVER_TITLE');
Text::script('COM_SPPAGEBUILDER_LAYOUT_POPOVER_CUSTOM_COLUMNS');
Text::script('COM_SPPAGEBUILDER_LAYOUT_POPOVER_INVALID_LAYOUT');
Text::script('COM_SPPAGEBUILDER_LAYOUT_NO_LAYOUT_FOUND');
Text::script('COM_SPPAGEBUILDER_LAYOUT_BACK');
Text::script('COM_SPPAGEBUILDER_LAYOUT_FILTER_RESET');
Text::script('COM_SPPAGEBUILDER_LAYOUT_FILTER_TITLE_ASC');
Text::script('COM_SPPAGEBUILDER_LAYOUT_FILTER_TITLE_DESC');
Text::script('COM_SPPAGEBUILDER_LAYOUT_FILTER_TITLE_POPULAR_FIRST');

Text::script('COM_SPPAGEBUILDER_INVALID_DEEP_ADDON');
Text::script('COM_SPPAGEBUILDER_TOTAL_ENTRIES');

Text::script('COM_SPPAGEBUILDER_CREATED_DATE');
Text::script('COM_SPPAGEBUILDER_CREATED_BY');
Text::script('COM_SPPAGEBUILDER_NO_ADDON_FOUND');
Text::script('COM_SPPAGEBUILDER_NO_SECTION_FOUND');
Text::script('COM_SPPAGEBUILDER_NOTHING_FOUND_FOR_KEYWORD');
Text::script('COM_SPPAGEBUILDER_NOTHING_FOUND');
Text::script('COM_SPPAGEBUILDER_NO_PAGE_FOUND');

Text::script('COM_SPPAGEBUILDER_INTERACTION_FIND_OUT');
Text::script('COM_SPPAGEBUILDER_INTERACTION_EXPLORE');

Text::script('COM_SPPAGEBUILDER_OPEN_IN_NEW_TAB');
Text::script('COM_SPPAGEBUILDER_NO_FOLLOW');
Text::script('COM_SPPAGEBUILDER_NO_REFERRER');
text::script('COM_SPPAGEBUILDER_NO_OPENER');

Text::script('COM_SPPAGEBUILDER_REPLACE_ICON');
Text::script('COM_SPPAGEBUILDER_CHOOSE_ICON');
Text::script('COM_SPPAGEBUILDER_ICON_LIBRARY');
Text::script('COM_SPPAGEBUILDER_UPLOAD_ICON');
Text::script('COM_SPPAGEBUILDER_SUPPORTED_ICON');
Text::script('COM_SPPAGEBUILDER_NO_ICON_FOUND');

Text::script('COM_SPPAGEBUILDER_ANIMATION');
Text::script('COM_SPPAGEBUILDER_ANIMATION_DESC');

Text::script('COM_SPPAGEBUILDER_INTERACTION_SETTINGS');
Text::script('COM_SPPAGEBUILDER_NO_ACTION_SELECTED');
Text::script('COM_SPPAGEBUILDER_SELECT_AN_ACTION');
Text::script('COM_SPPAGEBUILDER_TIMELINE');

Text::script('COM_SPPAGEBUILDER_BLANK_SPACE');

// Toaster
Text::script('COM_SPPAGEBUILDER_TOASTER_SUCCESS');
Text::script('COM_SPPAGEBUILDER_TOASTER_ERROR');

// Typography
Text::script('COM_SPPAGEBUILDER_GLOBAL_FONT');
Text::script('COM_SPPAGEBUILDER_GLOBAL_SIZE');
Text::script('COM_SPPAGEBUILDER_GLOBAL_LINE_HEIGHT');
Text::script('COM_SPPAGEBUILDER_GLOBAL_LETTER_SPACE');
Text::script('COM_SPPAGEBUILDER_ADDON_TAB_STYLE');
Text::script('COM_SPPAGEBUILDER_GLOBAL_WEIGHT');
Text::script('COM_SPPAGEBUILDER_GLOBAL_FONT_WEIGHT');
Text::script('COM_SPPAGEBUILDER_TYPOGRAPHY_FONT_THIN');
Text::script('COM_SPPAGEBUILDER_TYPOGRAPHY_FONT_EXTRA_LIGHT');
Text::script('COM_SPPAGEBUILDER_TYPOGRAPHY_FONT_LIGHT');
Text::script('COM_SPPAGEBUILDER_TYPOGRAPHY_FONT_NORMAL');
Text::script('COM_SPPAGEBUILDER_TYPOGRAPHY_FONT_MEDIUM');
Text::script('COM_SPPAGEBUILDER_TYPOGRAPHY_FONT_SEMI_BOLD');
Text::script('COM_SPPAGEBUILDER_TYPOGRAPHY_FONT_BOLD');
Text::script('COM_SPPAGEBUILDER_TYPOGRAPHY_FONT_EXTRA_BOLD');
Text::script('COM_SPPAGEBUILDER_TYPOGRAPHY_FONT_BLACK');
Text::script('COM_SPPAGEBUILDER_TYPOGRAPHY_SELECT_FONT_PLACEHOLDER');

// Dashboard
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_TITLE');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_SUBTITLE');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_ADD_NEW_PAGE');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_DELETE_DIALOG_MSG');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_TRASH_DIALOG_MSG');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_SEARCH_PAGES');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_COLUMN_HITS');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_COLUMN_ACCESS');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_COLUMN_AUTHOR');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_COLUMN_LANGUAGE');

Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_FILTER_BULK_ACTION');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_FILTER_PUBLISHED');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_FILTER_PUBLISH');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_FILTER_UNPUBLISHED');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_FILTER_UNPUBLISH');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_FILTER_TRASHED');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_FILTER_TRASH');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_CHECK_OUT');

Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_APPLY');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_CLEAR');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_ALL');

Text::script('JGLOBAL_SORT_BY');
Text::script('JGRID_HEADING_ORDERING_ASC');
Text::script('JGRID_HEADING_ORDERING_DESC');
Text::script('JSTATUS_ASC');
Text::script('JSTATUS_DESC');
Text::script('JGLOBAL_TITLE_ASC');
Text::script('JGLOBAL_TITLE_DESC');
Text::script('JGRID_HEADING_ACCESS_ASC');
Text::script('JGRID_HEADING_ACCESS_DESC');
Text::script('JAUTHOR_ASC');
Text::script('JAUTHOR_DESC');
Text::script('JDATE_ASC');
Text::script('JDATE_DESC');
Text::script('JGLOBAL_HITS_ASC');
Text::script('JGLOBAL_HITS_DESC');
Text::script('JGRID_HEADING_ID_ASC');
Text::script('JGRID_HEADING_ID_DESC');
Text::script('JGRID_HEADING_LANGUAGE_ASC');
Text::script('JGRID_HEADING_LANGUAGE_DESC');
Text::script('JCATEGORY');

Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_ADDONS_TITLE');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_ADDONS_SUBTITLE');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_ADDONS_SEARCH_PLACEHOLDER');

Text::script('COM_SPPAGEBUILDER_LAYOUT_SEARCH_PLACEHOLDER');

Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_ICON_TITLE');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_ICON_SUBTITLE');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_ICON_UPLOAD_BUTTON');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_ICON_CONTENT');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_ICON_DELETE_BUTTON');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_ICON_DUPLICATE_BUTTON');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_ICON_NOT_FOUND');

Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_INTEGRATIONS_TITLE");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_INTEGRATIONS_SUBTITLE");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_INTEGRATIONS_PRO_BUTTON");

Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_LANGUAGE_TITLE");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_LANGUAGE_SUBTITLE");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_LANGUAGE_COLUMN_TITLE");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_LANGUAGE_COLUMN_STATUS");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_LANGUAGE_COLUMN_VERSION");

Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_TITLE");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_SUBTITLE");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_LOADING");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_SAVE_BUTTON");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_SIDEBAR_OPTION");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_SIDEBAR_LICENSE");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_OPTION");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_PRODUCTION_MODE");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_PRODUCTION_MODE_DESC");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_PRODUCTION_MODE_LOADING");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_PURGER_CSS");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_INSTAGRAM_TOKEN");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_FACEBOOK_ID");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_FACEBOOK_ID_DESC");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_FACEBOOK_SECRET");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_GENERAL_TOKEN");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_DISABLED_GOOGLE_FONT");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_DISABLED_GOOGLE_FONT_DESC");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_LOAD_FONT_AWESOME");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_LOAD_FONT_AWESOME_DESC");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_LAZY_LOAD");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_LAZY_LOAD_DESC");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_PLACEHOLDER_IMAGE");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_PLACEHOLDER_IMAGE_DESC");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_DISABLED_CSS_ANIMATION");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_DISABLED_CSS_ANIMATION_DESC");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_DISABLED_DEFAULT_CSS");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_DISABLED_DEFAULT_CSS_DESC");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_OPEN_GRAPH");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_DISABLED_BUTTON");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_DISABLED_BUTTON_DESC");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_DISABLED_TWITTER_CARD");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_GOOGLE_MAP_API");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_SETTINGS_GOOGLE_MAP_API_DESC");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_LICENSE_UPDATE");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_MAIL_ADDRESS");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_LICENSE_KEY");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_FIND_LICENSE_KEY");


Text::script("COM_SPPAGEBUILDER_DASHBOARD_SIDEBAR_PAGES");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_SIDEBAR_ADDONS");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_SIDEBAR_CUSTOM_ICONS");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_SIDEBAR_INTEGRATIONS");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_SIDEBAR_LANGUAGES");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_SIDEBAR_SETTINGS");
Text::script('COM_SPPAGEBUILDER_DASHBOARD_SIDEBAR_CATEGORIES');

Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_MENU_COPY_LINK");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_MENU_COPY_LINK_SUCCESS_MSG");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_MENU_COPY_LINK_ERROR_MSG");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_MENU_ADD_TO_MENU");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_MENU_VIEW");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_MENU_DELETE");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_MENU_EXPORT");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_RENAME");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_MENU_ITEM");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_MENU_ITEM_ALIAS");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_MENU_ITEM_TITLE");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_MENU");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_MENU_PARENT_ITEMS");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_MENU_ASSIGNED_ERROR_MSG");

// Dashboard Home
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_COLUMN_TITLE');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_COLUMN_DATE');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_COLUMN_STATUS');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_COLUMN_STATUS_ENABLED');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_COLUMN_STATUS_DISABLE');
Text::script('COM_SPPAGEBUILDER_DASHBOARD_PAGES_COLUMN_ID');

Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_DIALOG_TITLE");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_DIALOG_CONTENT");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_DIALOG_SAVE_BUTTON");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_DIALOG_CANCEL_BUTTON");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_NEW_PAGES_DIALOG_TITLE");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_NEW_PAGES_DIALOG_PLACEHOLDER");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_NEW_PAGES_DIALOG_ERROR");
Text::script("COM_SPPAGEBUILDER_DASHBOARD_PAGES_LOAD_MORE_BUTTON");

Text::script("COM_SPPAGEBUILDER_DASHBOARD_BACK_TO_ADMIN");
Text::script("COM_SPPAGEBUILDER_ADDON_VIDEO_TITLE_DEFAULT_TEXT");
Text::script("COM_SPPAGEBUILDER_EXIT_EDITOR");

Text::script("COM_SPPAGEBUILDER_TOP_PANEL_CLOSE");
Text::script("COM_SPPAGEBUILDER_TOP_PANEL_EXPORT");
Text::script("COM_SPPAGEBUILDER_TOP_PANEL_IMPORT");
Text::script("COM_SPPAGEBUILDER_TOP_PANEL_CLEAR_CONTENT");
Text::script("COM_SPPAGEBUILDER_TOP_PANEL_VALIDATE_CONTENT");

Text::script("COM_SPPAGEBUILDER_VALIDATE_JSON_MODAL_TITLE_1");
Text::script("COM_SPPAGEBUILDER_VALIDATE_JSON_MODAL_TITLE_2");
Text::script("COM_SPPAGEBUILDER_VALIDATE_JSON_MODAL_HEADING_1");
Text::script("COM_SPPAGEBUILDER_VALIDATE_JSON_MODAL_HEADING_2");
Text::script("COM_SPPAGEBUILDER_VALIDATE_JSON_MODAL_HEADING_3");
Text::script("COM_SPPAGEBUILDER_VALIDATE_JSON_NOW_FIXING");
Text::script("COM_SPPAGEBUILDER_VALIDATE_JSON_MODAL_WHAT_HAPPENED");
Text::script("COM_SPPAGEBUILDER_VALIDATE_JSON_MODAL_RECOMMEND");
Text::script("COM_SPPAGEBUILDER_VALIDATE_JSON_MODAL_CANCEL");
Text::script("COM_SPPAGEBUILDER_VALIDATE_JSON_FIX_JSON");
Text::script("COM_SPPAGEBUILDER_VALIDATE_JSON_MODAL_SAVING_INSTRUCTION");
Text::script("COM_SPPAGEBUILDER_VALIDATE_JSON_MODAL_BUTTON_UNDERSTAND");

Text::script("COM_SPPAGEBUILDER_GLOBAL_BORDER");
Text::script("COM_SPPAGEBUILDER_GLOBAL_BORDER_STYLE_NONE");
Text::script("COM_SPPAGEBUILDER_GLOBAL_BORDER_STYLE_SOLID");
Text::script("COM_SPPAGEBUILDER_GLOBAL_BORDER_STYLE_DOUBLE");
Text::script("COM_SPPAGEBUILDER_GLOBAL_BORDER_STYLE_DOTTED");
Text::script("COM_SPPAGEBUILDER_GLOBAL_BORDER_STYLE_DASHED");
Text::script("COM_SPPAGEBUILDER_GLOBAL_BORDER_STYLE_GROOVE");
Text::script("COM_SPPAGEBUILDER_GLOBAL_BORDER_STYLE_RIDGE");
Text::script("COM_SPPAGEBUILDER_GLOBAL_BORDER_STYLE_INSET");
Text::script("COM_SPPAGEBUILDER_GLOBAL_BORDER_STYLE_OUTSET");

Text::script("COM_SPPAGEBUILDER_EDITOR_ACTION_PANEL_CLEAR_CLIPBOARD_TOOLTIP");
Text::script("COM_SPPAGEBUILDER_ACTION_CLEARED_CLIPBOARD_MESSAGE");